### ISSUE TITLE
Any information about future of the module?

### ISSUE THREAD

**Issue by vladim1** [communityii/yii2-user#19]
Could anybody share the information if this module is going to be updated? And if yes, then when? It looks great and promises to be awesome, but it's very outdated...

**Comment by kartik-v** [comment]
While would like to -- really strapped with time. It needs some effort to be put in to get it to a working standard for others. A user module needs to be simple yet configurable for various scenarios.

A lot of things in yii2 have evolved like the authclient - so using a user module needs to be a bit different than what it was for yii 1.x. Feel free to submit your thoughts on how to accelerate - but in my opinion this needs some time and it may not be immediate future unless we have support.

**Comment by kartik-v** [comment]
Module has been updated to an initial usable release (though not tested fully)... if you are willing to help with a few things as mentioned in #21 let know
