### ISSUE TITLE
Unknown scenario: default

### ISSUE THREAD

**Issue by jomonkj** [communityii/yii2-user#20]
after configured. i got error
`Unknown scenario: default`.

I solved this using https://github.com/yiisoft/yii2/issues/655

But can't log into backend after entering correct username and password.
again showing login page.

**Comment by izemize** [comment]
hy. you overwrite scenario method in model. But, you need extend scenario. so..

```php

    const SCENARIO_JOIN = 'Join';

    public function scenarios()
    {
        $scenarios = parent::scenarios();
        $scenarios[self::SCENARIO_JOIN] = ['email','name','username','birthdate','gender','password','passagain'];
        return $scenarios;
    }

    public function rules()
    {
        return [
            [['email','name','username','birthdate','gender','password','passagain'],'required','on'=>self::SCENARIO_JOIN],


```

**Comment by kartik-v** [comment]
Module has been updated to an initial usable release (though not tested fully)... Check #21.
