### ISSUE TITLE
Using module in advanced application template

### ISSUE THREAD

**Issue by vladim1** [communityii/yii2-user#22]
Can this module be used with advanced application template?
I want the administrative functions be enabled in backend and registraction, profile etc functions be enabled in frontend. There should be convenient way to do it easy.

**Comment by kartik-v** [comment]
Yes.

**Comment by vladim1** [comment]
If the module can be used in advanced application template by the proper configuration - THAT'S GREAT. It's hard to find all opportunities without full doc. I have seen the request to contribute to markdown in #21. But IMO it's hard to contribute to documentation when the person is not the author of the code. The person doesn't realize all features and intentions.

**Comment by kartik-v** [comment]
You may [read through this webtip](http://webtips.krajee.com/different-backend-frontend-sessions-yii-advanced-app/) to configure different sessions for frontend and backend.

I will be creating a separate app template (based on advanced, app-practical-a apps) that will have this module preinstalled with configurations.

**Comment by kartik-v** [comment]
[Updated in docs](https://github.com/communityii/yii2-user/blob/master/README.md#usage-with-yii-2-advanced-application-template).

**Comment by vladim1** [comment]
@kartik-v Thanks!!!
