### ISSUE TITLE
Got an error during updating the user profile

### ISSUE THREAD

**Issue by vladim1** [communityii/yii2-user#24]
I have updated the user profile and pressed 'Save' button. I've gotten an exception.
```
PHP Fatal Error – yii\base\ErrorException
Call to undefined method kartik\helpers\Enum::timeInterval()

    1. in /var/www/user/vendor/communityii/yii2-user/Module.php at line 959
    
```
which points at this line
```
'time' => Enum::timeInterval($seconds, '')
```
in ```timeLeft()``` method.

**Comment by kartik-v** [comment]
you need to ensure latest update of `yii2-helpers` - as mentioned in #23 - ensure the related extensions are updated
