### ISSUE TITLE
Create repositories

### ISSUE THREAD

**Issue by derekisbusy** [communityii/yii2-user#38]
@kartik-v Can you create two new repositories under communityii. I don't have perms to create repos.

- **yii2-common** For a collection of common elements that can be used in other projects ie. traits etc.
- **yii2-user-rbac-plugin** We can turn the rbac handler into a plugin and use it as a demo on how to create plugins.
- **yii2-email-manager** a module for managing mail templates I started.

**Comment by kartik-v** [comment]
- Is creating a `yii2-rbac` repo better so that it can be embedded with any user management module?
- I created a blank repo earlier to manage mails called [kartik-v/yii2-mailer](https://github.com/kartik-v/yii2-mailer). Check this and a discussion kartik-v/yii2-mailer#1  and can merge this here -- thinking of using SummerNote as an editor for mail management.

**Comment by kartik-v** [comment]
I have created the repos and given access.

I invited @andrewblake1 to join and contribute as well.

**Comment by kartik-v** [comment]
I have created the repos and given access.

I invited @andrewblake1 to join and contribute as well.

I agree the entire RBAC and MAILER functionality must be moved to separate extension.

Also make this extension as basic as it can be for a simple use case.

**Comment by derekisbusy** [comment]
What I was thinking is having repos that if they end in 'plugin' then they are considered a plugin of another repo.

- **yii2-user-rbac-plugin** plugin for adding rbac to yii2-user extension.
- **yii2-rbac-manager** separate extension for managing rbac
- **yii2-user-rbac-manager-plugin** - plugin for yii2-user that integrates Yii2-rbac-manager e.g. button that connects user views.
- **yii2-rbac-manager-user-plugin** plugin for yii2-rbac-manager that integrates Yii2-user e.g. button that connects user views.
- **yii2-email-manager** a separate extension
- **yii2-email-manager-user-plugin** ...

**Comment by kartik-v** [comment]
OK...can we decide the various plugin components to yii2 user module and define one consistent approach to all plugins.

**Comment by kartik-v** [comment]
At this stage let's then focus on the `yii2-user` extension first and then enable plugins to be added.
We can remove all other code beyond core user management (currently `RBAC` and `Mailer` out of this extension) and move that separately

For plugins:

I have updated additional repos to the following:

- `yii2-user-rbac-plugin`: For plugging in any RBAC module to yii2-user easily. Can include a default RBAC implementation that can be extended (maybe create a separate `yii2-rbac` extension later)
- `yii2-user-mailer-plugin`: For plugging in a mailer feature to yii2-user easily. Can include a default mailer management implementation that can be extended.

**Comment by derekisbusy** [comment]
I added PLUGINS.md to the yii2-common repo describing my concept of a plugin. Please let me know what you think. I'm still not sure what the best approach would be as far as loading plugins, and whether each pluggable component should have it's own DI container etc. I have two other projects I have to complete so won't be able to add any updates until next week.

**Comment by kartik-v** [comment]
Thanks. Just glanced quickly through it and looks fine. Will update on any further ideas after doing some study in detail.
