### ISSUE TITLE
Create migration & models

### ISSUE THREAD

**Issue by schmunk42** [communityii/yii2-user#4]
Use migrations instead of an SQL dump.

We can use the configured table prefix, like the advanced app now does: https://github.com/yiisoft/yii2/blob/master/apps/advanced/console/migrations/m130524_201442_init.php#L14

Just as a note: Usually migrations **must not** be changed after they've been pushed to the repo. There may be exceptions to this rule for initial development, but when we've released a first version, this is a very important convention.

**Comment by kartik-v** [comment]
See #21.
