### ISSUE TITLE
Errors during social authentication

### ISSUE THREAD

**Issue by vladim1** [communityii/yii2-user#40]
I have a problem with using social authentication in the module. I have tested Twitter and Facebook.
And I am getting 404 error (Page not found) all the time. I have found a few problems:
1) When I use facebook I get the following attributes:
```
[
    [name] => Name Lastname
    [email] => email@email.com
    [id] => 111111111111
]
```
When I use twitter I get the following attributes:
```
[
    [id] => 1111111111
    [id_str] => 1111111111111
    [name] => name
    [screen_name] => screen_name
    [location] => 
    [description] => 
    [url] => 
    [entities] => Array
        (
            [description] => Array
                (
                    [urls] => Array
                        (
                        )

                )

        )
    [protected] => 
    [followers_count] => 0
    [friends_count] => 0
    [listed_count] => 0
    [created_at] => Date Month Day time
    [favourites_count] => 0
    [utc_offset] => 
    [time_zone] => 
    [geo_enabled] => 
    [verified] => 
    [statuses_count] => 0
    [lang] => en
    [contributors_enabled] => 
    [is_translator] => 
    [is_translation_enabled] => 
    [profile_background_color] => value
    [profile_background_image_url] => value
    [profile_background_image_url_https] => value
    [profile_background_tile] => 
    [profile_image_url] => value
    [profile_image_url_https] => value
    [profile_link_color] => value
    [profile_sidebar_border_color] => value
    [profile_sidebar_fill_color] => value
    [profile_text_color] => value
    [profile_use_background_image] => value
    [has_extended_profile] => 
    [default_profile] => value
    [default_profile_image] => value
    [following] => 
    [follow_request_sent] => 
    [notifications] => 
]
```
But in the code we check ```login``` attribute, that is not in the list - [code](https://github.com/communityii/yii2-user/blob/master/controllers/AccountController.php#L156). If I change ```login``` key to ```name``` I am getting validation error during saving. Because the name contains spaces ```
Lastname Name```

BTW, the attributes from facebook, that I have gotten, don't have ```username``` attribute, that was checked [here](https://github.com/communityii/yii2-user/blob/master/controllers/AccountController.php#L143)

I also get a 404 error all the time. My script went to the [point](https://github.com/communityii/yii2-user/blob/master/controllers/AccountController.php#L182), but I have still gotten an Error 404. I was expecting a message ``` 'Error authenticating social client' ```. And this is strange.

**Comment by vladim1** [comment]
@derekisbusy 
I have seen the enhancements in the code. But now, when I am trying to update the package via composer, I am getting an error
```
composer update
```
```
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.                

  Problem 1
    - communityii/yii2-user dev-master requires comyii/yii2-common * -> no matching package found.
    - communityii/yii2-user dev-master requires comyii/yii2-common * -> no matching package found.
    - Installation request for communityii/yii2-user @dev -> satisfiable by communityii/yii2-user[dev-master].

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.
```
I have 
```
"communityii/yii2-user": "@dev"
```
in my composer.json

**Comment by vladim1** [comment]
After updating the package I am getting an error (while using Facebook)
```
Calling unknown method: yii\authclient\clients\Facebook::getEmail()
```
at [line](https://github.com/communityii/yii2-user/blob/master/controllers/AccountController.php#L121)
```php
$email = $client->getEmail();
```

**Comment by derekisbusy** [comment]
Use `comyii\user\clients\Facebook` for your social auth class. The social auth still isn't fully implemented. Needs work. This project is till under development.

**Comment by kartik-v** [comment]
All social authorization has been moved to `comyii\user\social` namespace.

Use `comyii\user\social\FacebookAuth` for Facebook authorization.

**Comment by vladim1** [comment]
@kartik-v 
@derekisbusy 
I am using ```comyii\user\social\FacebookAuth```
I am still getting an error 
```
Not Found (#404)
```
during
```php
$auth->save()
```
[here](https://github.com/communityii/yii2-user/blob/master/controllers/AccountController.php#L192)
I'm getting an exception and can't find out where does this exception occurs. BTW ```$auth->validate()``` passes and doesn't return errors.
I have tried:
```php
if ($user->save() && $auth->save()) {
    echo "Saved";
    exit(0);
    $transaction->commit();
    Yii::$app->user->login($user);
    $event->result = AuthEvent::RESULT_SIGNUP_SUCCESS;
    $event->flashType = 'success';
    $event->message = Yii::t(
        'user',
        'Logged in successfully with your <b>{client}</b> account.',
        ['client' => $clientTitle]
    );
} else {
    echo "Isn't saved";
    exit(0);
    $event->result = AuthEvent::RESULT_SIGNUP_ERROR;
    $event->flashType = 'error';
    $event->message = Yii::t(
        'user',
        'Error while authenticating <b>{client}</b> account.<pre>{errors}</pre>',
        ['client' => $clientTitle, 'errors' => print_r($user->getErrors(), true)]
    );
    throw new Exception('Error authenticating social client');
}
```
and I still get #404

**Comment by kartik-v** [comment]
You may check now.

**Comment by vladim1** [comment]
When I go to ```/user/register``` I am getting an exception
```
Unknown Property – yii\base\UnknownPropertyException
Setting unknown property: comyii\user\widgets\RegistrationForm::type
```
When I use Facebook for social authentication I am getting an information in ```print_r``` format
```
comyii\user\models\SocialProfile Object ( [_module:protected] => comyii\user\Module Object ( [installAccessCode] => ...
```

**Comment by kartik-v** [comment]
Ensure you have the most updated version of the extension from dev-master. Thw above things have been fixed with the various commits.
