### ISSUE TITLE
Revamp events and refactor/reformat code

### ISSUE THREAD

**Issue by kartik-v** [communityii/yii2-user#45]
- All event traits are removed and base events classes are used instead (thereby avoid declaring public properties in traits for classes)
- Added unavailable `comyii\user\events\admin\CreateEvent`
- Revamped clients and included `ClientTrait` and base `Client` class
- Renamed client classes to end with `Auth` for consistency
- Move all social authentication classes and methods to `social` folder and namespace
- Moved `EmailException` class to components folder
- Revamped PHP Documentation and edited various classes
- Various code formatting updates

**Comment by kartik-v** [comment]
@derekisbusy ... FYI... I am incorporating updates to the repo via this issue.

**Comment by derekisbusy** [comment]
Okay, I just pushed what I have for now. Also I moved the clients to `comyii\user\authclient\clients` to match that of the `yii\authclient\clients` structure.
